#! /usr/bin/env python

from optparse import OptionParser

from bluesocket import bluesocket

def runfile(filename, address, verbose):
    if verbose: print "# reading a file '%s'"%filename
    code="".join(open(filename).readlines())

    if verbose: print "# connecting to %s..."%address
    b = bluesocket()
    b.connect(address,5)
    if verbose: print "# sending the file..."
    b.send(code)
    if verbose: print "# receiving results..."
    print b.recv()
    b.close()

def main():
    usage = "usage: %prog [options] filename"
    parser = OptionParser(usage)
    parser.add_option("-b", "--bluetooth", 
            help = "connect to this bluetooth device", dest = "address",
            default = "00:19:79:86:EB:BC")
    parser.add_option("-v", "--verbose", 
            action = "store_true", dest = "verbose", default = False)
    (options, args) = parser.parse_args()
    if len(args) == 1:
        runfile(args[0], options.address, options.verbose)
    else:
        parser.error("incorrect number of arguments")

if __name__ == "__main__":
    main()
